sudo: no

language: python
python:
  - 3.4
  - 3.5

cache:
  directories:
  - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade setuptools
  - pip install cython
  - pip install flake8
  - pip install docutils
  - pip install coverage
  - pip install gunicorn
  - pip install pygments
  - python setup.py develop

script:
  - flake8 aiohttp
  - if python -c "import sys; sys.exit(sys.version_info < (3,5))"; then
        flake8 examples tests;
    fi
  - coverage run --source=aiohttp setup.py test
  - python setup.py check -rm

env:
  matrix:
    - PYTHONASYNCIODEBUG=nonemptystring AIOHTTP_NO_EXTENSIONS=
    - PYTHONASYNCIODEBUG=               AIOHTTP_NO_EXTENSIONS=
    - PYTHONASYNCIODEBUG=nonemptystring AIOHTTP_NO_EXTENSIONS=nonemptystring
    - PYTHONASYNCIODEBUG=               AIOHTTP_NO_EXTENSIONS=nonemptystring
